### ISSUE TITLE
Implementation of MemWitCreate

### ISSUE THREAD

**Issue by duyuefeng0708** [cambrian/accumulator#45]
I think we don't have the function for Witness generation for a particular element, except for using add_with_proof function when adding. But if I want to get the witness for an existing element inside the accumulator, how can I implement that?

**Comment by peymanr** [comment]
I think you can’t compute a witness unless you know all the elements in the
accumulator added after your element. If you know all those and the
accumulator value your element was added to, then add-with-proof on all
these elements can be used to generate a new updated witness.

**Comment by burdges** [comment]
Yes, you must know everything to make witnesses for accumulators.  If you want only partial information then you'll want Merkle trees, perhaps in zero-knowledge like zcash does.

**Comment by whaatt** [comment]
Hi all, and thanks for the question @duyuefeng0708! As the others have correctly pointed out, the TL;DR is **no**,  but it's instructive to see why.

Unfortunately, if all you have is the current accumulator value `a` in a vacuum, finding a witness `w` for an element `x` such that `w ^ x = a` is generally intractable for groups of unknown order (e.g. the cyclic subgroup of `RSA2048` generated by some generator `g`).

The intuition: If we write `w` as the `k`th power of a known generator `g`, we have `w ^ x = (g ^ k) ^ x = a` and in turn `(g ^ x) ^ k = a`. Solving the latter equation for some `k` requires taking the (difficult) [discrete log](https://en.wikipedia.org/wiki/Discrete_logarithm#Algorithms) of `a` base `g ^ x`.

---

Regarding the other comments: The ideal way to work with witnesses is to store them initially when `add_with_proof` is called, then to use `update_membership_witness` whenever untracked elements are added **or** deleted from the accumulator. More on witness updates in the [Wiki](https://github.com/cambrian/accumulator/wiki/Witness-Updates).

In this way, you don't need knowledge of the full accumulator set when updating witnesses (only the relevant changes), so long as you continually keep your witnesses up to date. The [`accumulator-demo`](https://github.com/cambrian/accumulator-demo) crate is an example of this usage pattern.

Hope this helps, and please let me know if there's anything I can clarify further!

**Comment by burdges** [comment]
As an aside, there are some provable limits on accumulators doing batch removals, and maybe on doing both batch additions (zcash) and any removes (this).

**Comment by duyuefeng0708** [comment]
Thanks for all your answers @peymanr @burdges @whaatt! That helps a lot. I was first reading another [implementation ](https://github.com/dignifiedquire/rust-accumulators)by Rust and within that repository they have this `MemWitCreate` function implemented. So I thought we might miss something here. But now it makes much more sense now, as in Dan Boneh's original paper, `MemWitCreate(A, S, x)` takes the whole set S as `visible` inputs, which is equivalent to the whole `add_with_proof` logic. I guess I did not get that before...

**Comment by whaatt** [comment]
Closing, but feel free to re-open if there are further questions.
