### ISSUE TITLE
Given an accumulator digest, how to compute the membership proof of an element in the set?

### ISSUE THREAD

**Issue by sshravan** [cambrian/accumulator#46]
Assume that I have access to all the elements of the set. 
How do I accomplish [1-5]?
```rust
  let acc = Accumulator::<Rsa2048, &'static str>::empty();
  let acc = acc.add(&["dog"]); // A = {"dog"}
  let acc = acc.add(&["cat"]); // A = {"dog", "cat"}
  let acc = acc.add(&["cow"]); // A = {"dog", "cat", "cow"}

  // 1. Get Membership proof of "dog" given acc and all elements in A
  // 2. Get Non-Membership proof of "pig", given acc and all elements in A
  // 3. Get Batch Membership proof of "dog" and "cat",  given acc and all elements in A

  // 4. Verify Membership proof of "dog" using acc and proof from 1.
  // 5. Verify Batch Membership proof of "dog" and "cat" using acc and proof from 3.
```

I prefer not using the ```update_membership_witness```.

Thanks in advance!

**Comment by whaatt** [comment]
Hey @sshravan, thanks for the question!

You can do (2) with just `acc` and the full set of elements.

For the rest, I'm wondering why you don't want to use `update_membership_witness`. Can you explain your use case a little more?

**Comment by sshravan** [comment]
Hey! Thanks.
Basically, I am looking for the memWitCreate from [page 14](https://eprint.iacr.org/2018/1188.pdf) that the library cites.  

Here is my use case though:
Assume that I have a trusted centralized accumulator manager that a client invokes to get the most up to date proof of an UTXO.
 
Hence the manager keeps track of the following:
```rust
Acc = {"dog", "cat", "cow"}  // Current UTXO set
Acc_digest = A // Current Digest of set Acc

current proof of "cow" = g ^ ("dog", "cat") = w
Verify proof of "cow" = w.g^("cow") == A
```

Hope it is clear.

**Comment by whaatt** [comment]
We don't have `MemWitCreate` exactly as described in the paper, but given the complete accumulator set, your centralized accumulator could easily compute the following:

```Rust
// Disclaimer: Haven't actually tried compiling this...
// ... `acc` defined previously ...

let empty_acc = Accumulator::<Rsa2048, &'static str>::empty();
let cow_witness = Witness(empty_acc([... all elements except "cow" ...]));

// If you have other elements/witnesses in the batch, add them to the array below:
let cow_membership_proof = acc.prove_membership([("cow", cow_witness)]);
```

That said, in general the end-users would not have to "track all the add-deletes" if you used `update_membership_witness`. Rather, they'd call `update_membership_witness` for their personal elements each time a change to the accumulator is broadcast over the network. The changes can be discarded as soon as the witness is updated.

I don't know all the specifics of your use case, but note that in the example above, the centralized source of truth has to nearly regenerate the entire accumulator to determine `cow_witness`. This could be an expensive operation in general.

Let me know if this helps!

**Comment by sshravan** [comment]
Thanks a lot for the help! It makes sense.  

On a different note, is there an equivalent of ```CreateAllMemWit``` ([Page 16](https://eprint.iacr.org/2018/1188.pdf))? Is it ```compute_individual_witnesses```?

**Comment by whaatt** [comment]
Yep! If you have a witness `w` for `N` elements, you can compute the witnesses for each individual element using `w.compute_individual_witnesses([... elements ...])` in `N log N` time.
