### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by BoltonBailey** [cambrian/accumulator#52]
Attempting to install using the instructions on the readme, I get the following error:

```
$ cargo run
    Updating git repository `https://github.com/cambrian/accumulator.git`
error: failed to load source for a dependency on `accumulator`

Caused by:
  Unable to update https://github.com/cambrian/accumulator.git

Caused by:
  failed to update submodule `docs`

Caused by:
  failed to fetch submodule `docs` from ssh://git@github.com/cambrian/accumulator.git

Caused by:
  failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded

Caused by:
  no authentication available
```

**Comment by whaatt** [comment]
Hi there, and thanks for the report!

This looks like an issue with your Git/Cargo setup; if you Google around for ``failed to authenticate when downloading repository attempted ssh-agent authentication, but none of the usernames `git` succeeded``, you'll find a number of potential causes and workarounds.

**Comment by BoltonBailey** [comment]
Thanks for the reply, after trying a few things, I managed to fix the problem by adding an ssh key to github.

Is there any way of doing this without an ssh key? I'm not sure if my collaborators all have one.
